---
title: "git_00"
author: "William Patrick Oliver"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
“The sun was shining on the sea,  
Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Now that my afro's as big as Shaft's  
I feel a little better about myself.  
How it warms my bullet-head in Winter,  
black halo, frizzy hat of hair.  
Shaft knew what a crown his was,  
an orb compared to the bush  
on the woman sleeping next to him.  
(There was always a woman  
sleeping next to him. I keep thinking,  
If I'd only talk to strangers. . .  
grow a more perfect head of hair.)  
His afro was a crown.  
Bullet after barreling bullet,  
fist-fights & car chases,  
three movies & a brief TV series,  
never one muffled strand,  
never dampened by sweat--  
I sweat in even the least heroic of situations.  